version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: eventrank-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
      POSTGRES_DB: eventrank
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
