-- =========================================
-- Eventos adicionais para popular a plataforma
-- =========================================
INSERT INTO eventos (nome, descricao, data_evento) VALUES
('Réveillon de Copacabana 2026', 'Uma das maiores festas de Ano Novo do mundo, com queima de fogos na praia de Copacabana e shows na orla.', '2026-01-01'),
('Carnaval de Salvador 2026', 'O maior carnaval de rua do mundo, com trios elétricos e shows ao longo do circuito Barra-Ondina.', '2026-02-14'),
('Carnaval do Rio de Janeiro 2026', 'Desfiles das escolas de samba no Sambódromo e blocos de rua espalhados pela cidade.', '2026-02-14'),
('Marchá de Frevo de Olinda 2026', 'Tradicional carnaval de Olinda, com bonecos gigantes e frevo pelas ladeiras históricas.', '2026-02-13'),
('Lollapalooza Brasil 2026', 'Festival de música multigênero realizado no Autódromo de Interlagos em São Paulo.', '2026-03-20'),
('São Paulo Fashion Week 2026', 'Uma das maiores semanas de moda da América Latina, reunindo estilistas nacionais e internacionais.', '2026-03-28'),
('Virada Cultural de São Paulo 2026', '24 horas de shows, exposições e atividades culturais gratuitas pela cidade.', '2026-05-16'),
('Festival de Inverno de Campos do Jordão 2026', 'Tradicional festival de música clássica realizado na serra paulista.', '2026-07-05'),
('Festa Junina de Campina Grande 2026', 'O ''Maior São João do Mundo'', com shows de forró e quadrilhas juninas.', '2026-06-06'),
('Bumba Meu Boi de São Luís 2026', 'Manifestação folclórica maranhense com bois decorados e apresentações populares.', '2026-06-24'),
('Festival Folclórico de Parintins 2026', 'Disputa entre os bois Garantido e Caprichoso em uma das maiores festas populares do Norte.', '2026-06-26'),
('Rock in Rio 2026', 'O maior festival de música do mundo, realizado no Rio de Janeiro com artistas nacionais e internacionais.', '2026-09-18'),
('The Town 2026', 'Festival de música em São Paulo criado pelos mesmos organizadores do Rock in Rio.', '2026-09-05'),
('Primavera Sound São Paulo 2026', 'Edição brasileira do festival espanhol, com line-up eclético de indie e eletrônica.', '2026-11-14'),
('Villa Mix Goiânia 2026', 'Um dos maiores festivais de música sertaneja do país.', '2026-05-09'),
('Festa do Peão de Barretos 2026', 'Tradicional rodeio e festival country, um dos maiores da América Latina.', '2026-08-20'),
('Oktoberfest Blumenau 2026', 'A maior festa alemã das Américas, com música, gastronomia e cerveja artesanal.', '2026-10-09'),
('Festival Gastronômico de Tiradentes 2026', 'Um dos mais tradicionais festivais gastronômicos do Brasil, na histórica cidade mineira.', '2026-08-14'),
('Bienal Internacional do Livro de São Paulo 2026', 'Um dos maiores eventos literários da América Latina.', '2026-08-27'),
('Bienal do Livro do Rio de Janeiro 2026', 'Feira literária carioca com lançamentos, autógrafos e debates.', '2026-11-05'),
('Festival de Cinema de Gramado 2026', 'Um dos festivais de cinema mais tradicionais do Brasil, na serra gaúcha.', '2026-08-15'),
('Mostra Internacional de Cinema de São Paulo 2026', 'Uma das maiores mostras de cinema do país, com filmes de todo o mundo.', '2026-10-16'),
('CCXP 2026', 'Comic Con Experience, o maior evento de cultura pop da América Latina, em São Paulo.', '2026-12-03'),
('Anime Friends 2026', 'Um dos maiores eventos de cultura pop japonesa do Brasil.', '2026-07-17'),
('Comic Con Experience Brasília 2026', 'Edição regional da CCXP com foco em quadrinhos, games e cultura pop.', '2026-04-25'),
('Campus Party Brasil 2026', 'Maior evento de tecnologia, inovação e cultura digital do país.', '2026-07-30'),
('Web Summit Rio 2026', 'Uma das maiores conferências de tecnologia e startups do mundo, edição brasileira.', '2026-04-15'),
('RD Summit 2026', 'Maior conferência de marketing e vendas da América Latina, realizada em Florianópolis.', '2026-10-08'),
('Futurecom 2026', 'Maior evento de telecomunicações e tecnologia da América Latina.', '2026-10-20'),
('São Paulo Tech Week 2026', 'Semana dedicada ao ecossistema de inovação e startups paulistano.', '2026-11-24'),
('GP Brasil de Fórmula 1 2026', 'Etapa brasileira do campeonato mundial de Fórmula 1, em Interlagos.', '2026-11-08'),
('Rio Open 2026', 'Principal torneio de tênis profissional da América do Sul.', '2026-02-16'),
('Maratona Internacional de São Paulo 2026', 'Uma das maiores maratonas da América Latina, pelas ruas de São Paulo.', '2026-04-12'),
('Meia Maratona Internacional do Rio 2026', 'Corrida de rua pela orla carioca, com vista para o Pão de Açúcar.', '2026-05-31'),
('Copa São Paulo de Futebol Júnior 2026', 'Tradicional torneio de base do futebol brasileiro.', '2026-01-10'),
('Réveillon de Fernando de Noronha 2026', 'Virada de ano em um dos destinos mais paradisíacos do Brasil.', '2026-01-01'),
('Festival de Verão de Salvador 2026', 'Festival de música com trios elétricos e grandes shows na orla soteropolitana.', '2026-01-17'),
('Festa de Iemanjá 2026', 'Celebração popular e religiosa na praia do Rio Vermelho, em Salvador.', '2026-02-02'),
('Círio de Nazaré 2026', 'Uma das maiores procissões católicas do mundo, em Belém do Pará.', '2026-10-11'),
('Festival de Dança de Joinville 2026', 'Um dos maiores festivais de dança do mundo, realizado em Santa Catarina.', '2026-07-22'),
('Salão do Automóvel de São Paulo 2026', 'Uma das maiores feiras automotivas da América Latina.', '2026-11-06'),
('Fenatran 2026', 'Maior feira de transporte rodoviário de cargas da América Latina.', '2026-10-27'),
('Agrishow 2026', 'Uma das maiores feiras de tecnologia agrícola do mundo, em Ribeirão Preto.', '2026-04-27'),
('Festival Do Chocolate de Gramado 2026', 'Celebração gastronômica dedicada ao chocolate, na serra gaúcha.', '2026-06-01'),
('Fenearte 2026', 'Feira Nacional de Negócios do Artesanato, realizada em Recife.', '2026-07-10'),
('Festa da Uva de Caxias do Sul 2026', 'Tradicional festa que celebra a cultura da imigração italiana no Rio Grande do Sul.', '2026-02-07'),
('Festival Internacional de Balonismo 2026', 'Espetáculo de balões coloridos no céu de Torres, no Rio Grande do Sul.', '2026-07-03'),
('Réveillon da Paulista 2026', 'Uma das maiores festas de Ano Novo de São Paulo, na Avenida Paulista.', '2026-01-01'),
('Festival Coquetel Molotov 2026', 'Festival de rock e cultura alternativa realizado em São Paulo.', '2026-06-13'),
('Tomorrowland Brasil 2026', 'Edição brasileira de um dos maiores festivais de música eletrônica do mundo.', '2026-10-17');
